theme: jekyll-theme-slate
# Site Settings
locale                   : "en"
title                    : "tensor4all"
markdown                 : "kramdown"
kramdown:
    math_engine: mathjax
    syntax_highlighter: rouge
